small fixes and IMessage
Rascass/chat_server pull request #6
Opened 2020-12-21 13:43 UTC by Vladiskos

2020-12-21 23:34 UTC, indasto commented on src/main/resources/config.properties
> +username=roo
root)

2020-12-22 07:27 UTC, shukal94 requested changes

2020-12-22 07:27 UTC, shukal94 commented on src/main/java/com/solvd/automation/lab/fall/listener/MyParser.java
> +
Objects.requireNotNull(parser, "parser was not recognized")

2020-12-22 07:27 UTC, shukal94 commented on src/main/java/com/solvd/automation/lab/fall/listener/MyParser.java
> +        } else if(parser.getClass() == ChecksumParser.class){
equals

2020-12-22 07:27 UTC, shukal94 commented on src/main/java/com/solvd/automation/lab/fall/main/Server.java
> +                new Thread(clientHandler).start();
add .join()

2020-12-22 07:27 UTC, shukal94 commented on src/main/java/com/solvd/automation/lab/fall/model/ClientHandler.java
> +
check if client token is not expired

2020-12-22 07:27 UTC, shukal94 commented on src/main/java/com/solvd/automation/lab/fall/model/ClientHandler.java
> +
see below

2020-12-23 14:40 UTC, shukal94 requested changes
one minor comment

2020-12-23 14:40 UTC, shukal94 commented on logs/log_roll.txt
>  2020:-12-22 04:48:31 [Thread-1] INFO  com.solvd.automation.lab.fall.model.ClientHandler - Searched client: Client{clientIp='127.0.0.1:52906', clientToken=72781, login='Anna', passwordHash=2045663, se
let's include that file to gitignore

2020-12-23 17:56 UTC, merged